language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install -r tst_requirements.txt

script:
  - cd resettabletimer
  - python -m unittest discover -s tst/
