language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install -r tst_requirements.txt
script:
- cd resettabletimer
- python -m unittest discover -s tst/
- cd ..
deploy:
  provider: pypi
  user: kangasta
  password:
    secure: WuM4apYm0TO5tjTmcbexssoBOVDknXwZlqaEhlKC5MESKaCT8RLS38OJ++zO1nhEaULYF5mI9dKhallB9ajPxERmxVQTGBF7xxJsk3BcDvutchiWIKBViw7IvS1TD9AqJkcr/jPZWzge2erOmtICTwLZ446W8UTGZ7vjFLDvFfz6IgwXgNBdl8DjfN1G3YEBizBsjxGdXU3JcYhlX6x6191xT4RtH3Idq4nfozVQuBG6vf+lMxJb8nYYG55LFmlZ2A6wJwCkcRdzcQUQUCisfgZvJyOEy2OokUKn437VBLfuIzGJf1jTKwuJvegRqWLEOuaY/QheleqzYxao3MPSNVv5/hAABPG+8PB0adaPyDYr6mXueVkQOPwOu1fkeywyflhRVOCSD0c0YGGc7B5P/ZAFred4zYttq+t8ja4XNAg/Z3LAXVlUn+tgzDw/p95qFtkKTScUtWsn1OVwH1aWmQJnJmuPn0opIVwDO1b5JL5OmMSocYluWixvITbYbgmdggAszohy1oadAlGDxkJrsQZsMNKawuG5qINoB1WWw5BmU+WdgkPUlNe6ieJH3JPl9zYh9HhsrnsUsP1KpBNlcV1kw4Wk9YKbT8cS9Hh7Ez5FhUuKaAruNeF0m2o/ANGZR53G2OqqrB/95v4YjMsCVLSFpHOh8eA8pIAAh4RPc7Y=
  on:
    tags: true
    python: 3.6
